name: Upload Docker Image using SCP

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout repository
      uses: actions/checkout@v2

    # List contents of docker-images to verify the file exists
    - name: List contents of docker-images directory
      run: ls -l ./docker-images

    # Check current working directory
    - name: Check current working directory
      run: pwd

    # Set file permissions for my-image-name.tar (if file exists)
    - name: Set file permissions for my-image-name.tar
      run: chmod 644 ./docker-images/my-image-name.tar

    # Set directory permissions for the docker-images directory
    - name: Set directory permissions for docker-images
      run: chmod 755 ./docker-images

    # Check if the file exists
    - name: Check if file exists
      run: ls -l ./docker-images/my-image-name.tar

    # Change ownership to current user if necessary
    - name: Change ownership to current user
      run: chown -R $USER:$USER ./docker-images/my-image-name.tar

    # Run the SCP action to upload the Docker image
    - name: Upload Docker image using SCP with Debug
      uses: appleboy/scp-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        source: ./docker-images/my-image-name.tar
        target: /remote/path/to/target/directory/
        port: 22
        debug: true
