name: Build and Deploy Docker Container via SSH

on:
  push:
    branches:
      - main  # Срабатывает при push в основную ветку (можно изменить)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Получаем исходный код репозитория
    - name: Checkout code
      uses: actions/checkout@v4

    # 2. Устанавливаем Docker Buildx (если нужно для дополнительных возможностей)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # 4. Строим Docker-образ
    - name: Build Docker image
      run: |
        docker build -t my-image-name:${{ github.sha }} .

    # 5. Отправляем Docker-образ в Docker Hub
    - name: Push Docker image to Docker Hub
      run: |
        docker push my-image-name:${{ github.sha }}

    # 6. Подключаемся через SSH и деплоим на удаленном сервере
    - name: SSH to server and deploy
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_IP }}  # IP удаленного сервера
        username: ${{ secrets.SERVER_USER }}  # Имя пользователя для SSH
        key: ${{ secrets.SERVER_SSH_KEY }}  # Приватный SSH-ключ для доступа
        script: |
          # Останавливаем старый контейнер (если он есть)
          docker stop my-container || true
          docker rm my-container || true

          # Запускаем новый контейнер с обновленным образом
          docker run -d --name my-container -p 8080:80 my-image-name:${{ github.sha }}

          # При необходимости выполните дополнительные команды
          # Например, перезапуск приложения или настройка переменных окружения.
